# Define input
string object_name # object name to grasp. This is used to generate grasp pose
geometry_msgs/Pose object_pose1 # initial object pose
geometry_msgs/Pose object_pose2 # target object pose
---
#Define output
# refer to: https://github.com/ros-planning/moveit_msgs/blob/master/msg/MoveItErrorCodes.msg
int32 result # error code
int32 SUCCESS=1
int32 FAILURE=99999
